server:
  port: 8090

jwt:
  secret: 8c1814d9ed125dda202a4b2cb4738ed4b59b2b42e3c31787b4c614915fa27d98

spring:
  application:
    name: bff-gateway

  cloud:
    gateway:
      routes:
        # ── Auth Service ──────────────────────────────
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - name: AddRequestHeader
              args:
                name: X-Internal-Service
                value: bff-gateway

        - id: users-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/users/**
          filters:
            - JwtValidation

        # ── Projects Service ──────────────────────────
        - id: projects-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/projects/**
          filters:
            - JwtValidation

        - id: clients-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/clients/**
          filters:
            - JwtValidation

        - id: phases-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/phases/**
          filters:
            - JwtValidation

        - id: tasks-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/tasks/**
          filters:
            - JwtValidation

      # CORS global
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true