server.port=8090

jwt.secret=8c1814d9ed125dda202a4b2cb4738ed4b59b2b42e3c31787b4c614915fa27d98

spring.application.name=bff-gateway

# ── Auth Service (libre) ──────────────────────────────
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0].name=AddRequestHeader
spring.cloud.gateway.routes[0].filters[0].args.name=X-Internal-Service
spring.cloud.gateway.routes[0].filters[0].args.value=bff-gateway

# ── Users Service (protegido) ─────────────────────────
spring.cloud.gateway.routes[1].id=users-service
spring.cloud.gateway.routes[1].uri=http://localhost:8080
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[1].filters[0]=JwtValidation

# ── Projects Service (protegido) ─────────────────────
spring.cloud.gateway.routes[2].id=projects-service
spring.cloud.gateway.routes[2].uri=http://localhost:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/projects/**
spring.cloud.gateway.routes[2].filters[0]=JwtValidation

# ── Clients Service (protegido) ──────────────────────
spring.cloud.gateway.routes[3].id=clients-service
spring.cloud.gateway.routes[3].uri=http://localhost:8081
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/clients/**
spring.cloud.gateway.routes[3].filters[0]=JwtValidation

# ── Phases Service (protegido) ───────────────────────
spring.cloud.gateway.routes[4].id=phases-service
spring.cloud.gateway.routes[4].uri=http://localhost:8081
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/phases/**
spring.cloud.gateway.routes[4].filters[0]=JwtValidation

# ── Tasks Service (protegido) ────────────────────────
spring.cloud.gateway.routes[5].id=tasks-service
spring.cloud.gateway.routes[5].uri=http://localhost:8081
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/tasks/**
spring.cloud.gateway.routes[5].filters[0]=JwtValidation

# ── Resources Service (protegido) ────────────────────
spring.cloud.gateway.routes[6].id=professionals-service
spring.cloud.gateway.routes[6].uri=http://localhost:8083
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/professionals/**
spring.cloud.gateway.routes[6].filters[0]=JwtValidation

spring.cloud.gateway.routes[7].id=skills-service
spring.cloud.gateway.routes[7].uri=http://localhost:8083
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/skills/**
spring.cloud.gateway.routes[7].filters[0]=JwtValidation

spring.cloud.gateway.routes[8].id=assignments-service
spring.cloud.gateway.routes[8].uri=http://localhost:8083
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/assignments/**
spring.cloud.gateway.routes[8].filters[0]=JwtValidation

spring.cloud.gateway.routes[9].id=availability-service
spring.cloud.gateway.routes[9].uri=http://localhost:8083
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/availability/**
spring.cloud.gateway.routes[9].filters[0]=JwtValidation

spring.cloud.gateway.routes[10].id=absences-service
spring.cloud.gateway.routes[10].uri=http://localhost:8083
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/absences/**
spring.cloud.gateway.routes[10].filters[0]=JwtValidation

# colaboracion

spring.cloud.gateway.routes[11].id=threads-service
spring.cloud.gateway.routes[11].uri=http://localhost:8084
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/threads/**
spring.cloud.gateway.routes[11].filters[0]=JwtValidation

spring.cloud.gateway.routes[12].id=comments-service
spring.cloud.gateway.routes[12].uri=http://localhost:8084
spring.cloud.gateway.routes[12].predicates[0]=Path=/api/comments/**
spring.cloud.gateway.routes[12].filters[0]=JwtValidation

spring.cloud.gateway.routes[13].id=activity-service
spring.cloud.gateway.routes[13].uri=http://localhost:8084
spring.cloud.gateway.routes[13].predicates[0]=Path=/api/activity/**
spring.cloud.gateway.routes[13].filters[0]=JwtValidation



# ── CORS global ───────────────────────────────────────
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true